[package]
name = "tfhela"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
serde = "1.0.203"
serde_json = "1.0.120"

[dev-dependencies]
proptest-derive = "0.5.0"
proptest = "1.5.0"
